### ISSUE TITLE
如何处理mysql返回的数据？

### ISSUE THREAD

**Issue by dong-lufei** [sail-sail/mysql2#2]
我连接数据库后，查询得到[ { id: 1, todo: "study", isCompleted: 1 } ]，那么如何拿到todo的值呢，我用数组下标0索引拿报错了

**Comment by sail-sail** [comment]
这不是普通的 js 对象数组吗?
```js
const result = [ { id: 1, todo: "study", isCompleted: 1 } ];
console.log(result[0].todo);

for (const item of result) {
  console.log(item.todo);
}
```

**Comment by dong-lufei** [comment]
> 这不是普通的 js 对象数组吗?
> 
> ```js
> const result = [ { id: 1, todo: "study", isCompleted: 1 } ];
> console.log(result[0].todo);
> 
> for (const item of result) {
>   console.log(item.todo);
> }
> ```

可以拿到result，但是一用result[0]取值，就报错，也不能循环：TS2488 [ERROR]: Type 'RowDataPacket[] | RowDataPacket[][] | OkPacket | OkPacket[] | ResultSetHeader' must have a '[Symbol.iterator]()' method that returns an iterator.

**Comment by sail-sail** [comment]
```ts
const result = await pool.query("SELECT 1") as any;

const result = <any>await pool.query("SELECT 1");
```
强制转换成any类型试试

**Comment by dong-lufei** [comment]
我插入一条数据 结果为：
 console.log(result[0])
 ```
ResultSetHeader {
  fieldCount: 0,
  infileName: undefined,
  affectedRows: 1,
  insertId: 7,
  info: "",
  serverStatus: 2,
  warningStatus: 0,
  stateChanges: undefined,
  changedRows: undefined
}
```
 console.log(result[0].affectedRows)也报错。  原来是类型呀  我加了 as any 就好了 拿到值了
