### ISSUE TITLE
文档介绍用法的内容太少了，比如CRUD

### ISSUE THREAD

**Issue by dong-lufei** [sail-sail/mysql2#6]
前端开发的人看这么点文档不知道如何使用的

```js
import * as mysql2 from "https://deno.land/x/mysql2@v1.0.6/mod.ts";

const pool = mysql2.createPool({
  host: "127.0.0.1",
  port: 3306,
  user: "root",
  password: "root",
  // database: "denomysql",
  connectionLimit: 4,
});
const result = await pool.query("show databases;");
console.log(result[0]);
await pool.end();
```
和 https://github.com/denodrivers/mysql 的区别优势是什么？

**Comment by sail-sail** [comment]
文档跟nodejs的mysql2是一模一样的, 看nodejs版本的mysql2即可, 现在 deno 也支持直接使用 nodejs 的 npm 包了, 可以改为直接用nodejs的npm里面的 mysql2
跟 mysql 唯一的区别是, mysql2 支持 PrepareStatement, 所以, 如果执行大量只是参数不同的sql语句, 会有一定的性能优势

**Comment by dong-lufei** [comment]
哦，对于新手不友好。html+css+js 之后直接来学deno的，现在还要去学nodejs先？ 走nodejs可能就不会使用deno了
